### PR TITLE
Fixes C++ example not using the correct encoder

### LINKED ISSUE #7: SwerveModule class doesn't set Duty Cycle encoder as the feedback device
https://www.chiefdelphi.com/t/sparkmax-c-pid-controller-with-maxswerve-not-functioning-as-expected/424387/2

### PR DESCRIPTION
**Pull request by r4stered**
Fixes #7

### CODE REVIEW

File: src/main/cpp/subsystems/MAXSwerveModule.cpp [hunk 1]
```diff
@@ -48,6 +48,10 @@ MAXSwerveModule::MAXSwerveModule(const int drivingCANId, const int turningCANId,
       kTurningEncoderPositionPIDMinInput.value());
   m_turningPIDController.SetPositionPIDWrappingMaxInput(
       kTurningEncoderPositionPIDMaxInput.value());
+        
+  // Sets the PID Controller to use the duty cycle cncoder on the swerve
```
Comment (jfabellera) [inline src/main/cpp/subsystems/MAXSwerveModule.cpp:52]:
```suggestion
  // Set the PID Controller to use the duty cycle encoder on the swerve
```

**Review by jfabellera — CHANGES_REQUESTED** [review]
Thanks for catching this, just some small things in the comment before merging
